---
title: "ISLR Chpt1"
Author: Doudou Zhang
---

----Question 8----

a&b
```{r}
College <- read.csv("Desktop/R/ISLR/College.csv")
rownames(College)=College[,1] 
#romove the first original column
College=College[,-1] 
fix(College)
```

c&d
```{r}
summary(College)
pairs(College[,1:10])
plot(College$Outstate, College$Private)
Elite=rep("No",nrow(College))
Elite[College$Top10perc>50]="Yes"
Elite=as.factor(Elite)
College=data.frame(College,Elite)
View(College)
```

e
```{r}
par(mfrow=c(2,2))
hist(College$Outstate)
hist(College$Apps)
hist(College$Enroll)
hist(College$Top10perc)
```


----Question 9----
a
```{r}
auto <- read.csv("Desktop/R/ISLR/Auto.csv",header=T, na.strings="?")
auto = na.omit(auto)
summary(auto)
names(auto)
```
Qualitative: name, origin
Quantitative:mpg,cylinders, displacement,"horsepower" "weight","acceleration","year"  

b&c
```{r}
auto = na.omit(auto)
sapply(auto[,1:7],range)
sapply(auto[,1:7],mean)
sapply(auto[,1:7],sd)

```

d
```{r}
auto = auto[-(10:85),]
sapply(auto[,1:7],range)
sapply(auto[,1:7],mean)
sapply(auto[,1:7],sd)
```

e
```{r}
auto <- read.csv("Desktop/R/ISLR/Auto.csv",header=T, na.strings="?")
auto = na.omit(auto)

par(mfrow=c(2,2))
hist(auto$mpg)
hist(auto$cylinders,col=3)
plot(auto$horsepower,auto$weight)

```

f
```{r}
pairs(auto)
```

----question 10----

a
```{r}
library(MASS)
#Boston
dim(Boston)
```

b
```{r}
pairs(Boston[,1:10])
```
c
```{r}
plot(Boston$age, Boston$crim)
plot(Boston$dis, Boston$crim)
plot(Boston$tax, Boston$crim)
```

d
```{r}
sapply(Boston, range)
par(mfrow=c(1,3))
hist(Boston$crim[Boston$crim>1], breaks=15)
hist(Boston$tax, breaks=25)
hist(Boston$ptratio, breaks=25)
```

e
```{r}
dim(subset(Boston, chas == 1))
```
35 suburbs

f
```{r}
median(Boston$ptratio)
```

g
```{r}
subset(Boston, medv == min(Boston$medv))
```
399 and 406 has the lowest median value of homes.

h
```{r}
dim(subset(Boston, rm > 7))
dim(subset(Boston, rm > 8))
```
64 suburbs have more than seven rooms per dwelling on average, while 13 suburbs have more than eight rooms per dwelling on average. 
